### ISSUE TITLE
Slow indexing of files accessed over network

### ISSUE THREAD

**Issue by tomas-pluskal** [PRIDE-Utilities/xxindex#1]
Hi,
I see extremely slow parsing of mzML files using the jmzml library that relies on xxindex for indexing. This happens when I access the mzML files over network (SMB share mounted on my Mac OS X system). It takes over 2 hours to parse a single 300 MB mzML file this way. The same file can be parsed in a few seconds when accessed locally. I believe the speed of xxindex is the issue, namely the fact that it reads the XML files byte-by-byte (!), as I found here: 

https://github.com/PRIDE-Utilities/xxindex/blob/master/src/main/java/psidev/psi/tools/xxindex/index/XmlXpathIndexer.java#L161

Is there anyone who could help me to debug and fix this issue?

Thanks,

Tomas

**Comment by tomas-pluskal** [comment]
Maybe @ypriverol ? :)

**Comment by javizca** [comment]
I am afraid @ypriverol is offline at the moment, he will be on holiday till January 11th without Internet connection. I had not heard this problem with xxindex before.

**Comment by tomas-pluskal** [comment]
I tested this issue on two mzML files, one 138MB and one 327MB large. I measured the time of a single function call:
```
MzMLIndexerFactory.getInstance().buildIndex(inputFile);
```
**Results**
file 1 (138 MB): 17 seconds when the file is on local drive, 32 minutes when the file is on network drive
file 2 (327 MB): 2 minutes when the file is on local drive, I killed the (still unfinished) indexing from network drive after 8 hours

Note: MzMLIndexerFactory is part of jmzml, but its function relies on xxindex, mainly using the StandardXpathAccess and SimpleXmlElementExtractor classes). See https://github.com/PRIDE-Utilities/jmzml/blob/master/src/main/java/uk/ac/ebi/jmzml/xml/xxindex/MzMLIndexerFactory.java

My HW configuration: Apple Macbook Air running Mac OS X 10.10.5, with a mounted network SMB file share. Network connection is 100 Mbit ethernet. I know that 100 Mbit ethernet is not the fastest nowadays, but the network is not rate-limiting here. I can copy the 327 MB file from the network in less than 3 minutes.

**Comment by tomas-pluskal** [comment]
Hi, did anyone had a chance to check this issue? @ypriverol ?

**Comment by ypriverol** [comment]
I will take a look during this week. @tomas-pluskal

**Comment by tomas-pluskal** [comment]
Thanks! Any news?

**Comment by tomas-pluskal** [comment]
I'm adding another user (@photocyte) who suffers from this issue, so he can watch it.

**Comment by tomas-pluskal** [comment]
Hi, I identified the source of this issue - it is the fact that the source XML file is opened again each time readBytes() is called, and then it is immediately closed. 

See https://github.com/PRIDE-Utilities/xxindex/blob/master/src/main/java/psidev/psi/tools/xxindex/SimpleXmlElementExtractor.java#L155
 
This is a rather poor design in terms of performance over network. Please take a look at my suggested fix in PR #2. This will cause a minor API change, but it will fix the jmzml performance issue as described above.

**Comment by ypriverol** [comment]
@tomas-pluskal I will merge the current version and do the proper test, and finally I will do a final release. Thanks for doing this.

**Comment by tomas-pluskal** [comment]
I think this is definitely a desirable change for jmzml. I do not know if there are any other projects relying on xxindex, that could potentially be affected by this change.

I also don't know if there is any specific use case for xxindex that could be disrupted by this change. But I doubt it.

**Comment by ypriverol** [comment]
@tomas-pluskal We have lot of them jmzIdentML and other readers, In any case I will do a full test. Our previous improvement was using woodstox http://wiki.fasterxml.com/WoodstoxHome . I will release a new version anf test all of our components.

**Comment by ypriverol** [comment]
@tomas-pluskal I will close the issue after the merge

**Comment by ypriverol** [comment]
@tomas-pluskal the major change you included is related with the constructor of the xxindex, we need to check all the libraries that rely on the older constructor. Have you tested the jmzML?

**Comment by tomas-pluskal** [comment]
I tested running the same code (see below), using the updated xxindex and jmzml. The inputFile is about 327 MB large.
```
MzMLIndexerFactory.getInstance().buildIndex(inputFile);
```

Run time when the file is on a local drive: 1 min 23 s
Run time when the file is on network: 3 min 1 s

Since I am connected to network over 100 Mbit ethernet, and the local drive is a fast SSD, I think this difference is reasonable. In my view, the update fixed the main performance issue of jmzml.

**Comment by tomas-pluskal** [comment]
If you don't like the change in the constructor, I can also use another approach: make a copy of the SimpleXmlElementExtractor under a different name (e.g., FastXmlElementExtractor), with the updated constructor. The underlying projects can still use the existing SimpleXmlElementExtractor, while jmzml can be updated to the new FastXmlElementExtractor.

We can also mark SimpleXmlElementExtractor as deprecated, to encourage the general transition to the FastXmlElementExtractor.

Let me know.

**Comment by ypriverol** [comment]
Please do it, I would like to give some time between versions and then in a future iteration we can remove the present constructor. Please try to comment the code in the deprecated constructor for future users. I will take care of the merge and the deploy of jmzML and jmzIdentML.

**Comment by tomas-pluskal** [comment]
Please take a look at the new PR. If you agree with the change, I would appreciate if you could make a new release of xxindex ASAP, so we can also update jmzml.

**Comment by ypriverol** [comment]
I will do it and I will do the changes in the jmzML and the release if you want. Or you can start to do the jmzML changes and I will do also the pull-request there.

**Comment by tomas-pluskal** [comment]
I will submit the pull request for jmzml.

**Comment by ypriverol** [comment]
Release done, version 0.16.

**Comment by tomas-pluskal** [comment]
Thanks for making the release promptly!

**Comment by ypriverol** [comment]
The jmzML release was also done, please check the new version and if is possible do the testing to check that everything works ok.

**Comment by tomas-pluskal** [comment]
All our tests passed fine with jmzml 1.7.4, so it looks good. Thanks.

**Comment by ypriverol** [comment]
Are you using jmzIdentML?

**Comment by tomas-pluskal** [comment]
Not at the moment.

**Comment by ypriverol** [comment]
jmzReader?

**Comment by ypriverol** [comment]
We have a common API for identification, quantitation and MS/MS files. Yo can use it more than happy to have contributions https://github.com/PRIDE-Utilities/ms-data-core-api

**Comment by tomas-pluskal** [comment]
Thanks, I have seen it.
We are using some of your parsers in our MSDK project (https://msdk.github.io/).

If you are planning future updates, I have a few suggestions:
- I think the libraries should distinguish random access (from File) and parsing the data formats from any InputStream. These are two different use cases (input stream can come from network, compressed file, or as a direct output of another software like msconvert).
- It should be possible to quickly parse all scan metadata from the files and access the spectral data points later using random access
- I think using Number[] arrays as an output of BinaryDataArrayList wastes a lot of memory, in comparison to primitive double[] arrays
